// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as AsyncData from "rescript-asyncdata/src/AsyncData.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.mjs";
import * as ReactUpdate from "rescript-react-update/src/ReactUpdate.mjs";

import './App.css'
;

function decode(data) {
  return {
          id: Json_decode.field("id", Json_decode.string, data),
          url: Json_decode.field("download_url", Json_decode.string, data)
        };
}

function App(Props) {
  var match = ReactUpdate.useReducer((function (state, action) {
          if (typeof action === "number") {
            if (action !== 0) {
              return {
                      TAG: /* Update */0,
                      _0: {
                        data: /* Loading */1
                      }
                    };
            } else {
              return {
                      TAG: /* SideEffects */2,
                      _0: (function (param) {
                          var send = param.send;
                          Curry._1(send, /* ApiLoading */1);
                          fetch("https://picsum.photos/v2/list/").then(function (prim) {
                                  return prim.json();
                                }).then(function (res) {
                                return Curry._1(send, /* ApiSuccess */{
                                            _0: Json_decode.array(decode, res)
                                          });
                              });
                          
                        })
                    };
            }
          } else {
            return {
                    TAG: /* Update */0,
                    _0: {
                      data: /* Done */{
                        _0: action._0
                      }
                    }
                  };
          }
        }), {
        data: /* NotAsked */0
      });
  var send = match[1];
  React.useEffect((function () {
          Curry._1(send, /* AskInitData */0);
          
        }), []);
  return React.createElement("div", {
              className: "grid gap-2 sm:gap-10 grid-cols-2 sm:grid-cols-3 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6"
            }, AsyncData.getWithDefault(AsyncData.map(match[0].data, (function (x) {
                        return Belt_Array.map(x, (function (item) {
                                      return React.createElement("img", {
                                                  key: item.id,
                                                  className: "justify-self-center h-full w-full object-cover object-center rounded-lg cursor-pointer",
                                                  src: item.url
                                                });
                                    }));
                      })), React.createElement("div", undefined, "NotAsked | Loading")));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
